###
POST http://localhost:5297/report
Content-Type: application/json

{
    "url": "/test.me/some-url"
}

### 
POST http://localhost:5297/report
Content-Type: application/json

{
    "url": "/test.me/some-other"
}

